name: DevSecOps CI/CD Pipeline
on:
  push:
    branches:
      - main

jobs:

  lint:
    uses: ./.github/workflows/lint.yml

  test:
   needs: lint
   uses: ./.github/workflows/test.yml

  artifact:
   needs: test
   uses: ./.github/workflows/build.yml


  images-scan:
   needs: [ lint, artifact ]
   uses: ./.github/workflows/security-scan.yml
   secrets: inherit

  docker-push: 
   needs: [ lint, images-scan, artifact ]
   uses: ./.github/workflows/docker.yml
   secrets: inherit

  deploy:
   needs: [ lint, images-scan, docker-push ]
   uses: ./.github/workflows/deploy.yml
   secrets: inherit